### ISSUE TITLE
Multisite support

### ISSUE THREAD

**Issue by martijnvanonz** [pierrestoffe/craft-language-redirector#12]
Hi,

I'm working on a multisite multi-locale project. The structure is 4 site group with each 2 languages. How should I set this up in the config? Or is the plugin not prepared for this?

**Comment by pierrestoffe** [comment]
Hi @martijnvanonz,

The plugin is indeed not supporting this Site architecture. But it's an interesting case and it totally matches what Craft is built for, so I'll make it my goal to release an update with support for multi-Site + multi-language before the end of the summer.

I'll update this issue once it's released.

**Comment by martijnvanonz** [comment]
Hi @pierrestoffe, 

Thank you for the fast reply. Looking forward to the feature. Will give the plugin an other try in a non-multi site project!

**Comment by nitech** [comment]
Yes, we need this one.

**Comment by JorgeAnzola** [comment]
This seems like a very nice feature to have. Upvoted!

**Comment by pierrestoffe** [comment]
@martijnvanonz @nitech @JorgeAnzola
If you currently have a project that could benefit from this feature, could I ask you to test an update?

You can replace the version of the plugin in composer with this one:
`"pierrestoffe/craft-language-redirector": "dev-develop#4f42716740e34d65c151add6f4a980190b327901"`
And then run `composer update`

To define the groups, simply update the `languages` setting in the _config/language-redirector.php file_ so that it matches this structure:
```
'languages' => [
    [
        'en' => 'english',
        'fr' => 'french',
        'nl' => 'dutch',
    ],
    [
        'en' => 'blueEnglish',
        'fr' => 'blueFrench',
    ]
]
```

Of course don't push this in production just yet. It isn't an official release.

**Comment by martijnvanonz** [comment]
Hi @pierrestoffe 

Could you elaborate more on how to structure the config file?
For example, I have 6 sites with the handles: 
siteADutch, siteAEnglish,
siteBDutch, siteBEnglish,
siteCDutch, siteCEnglish,

Could you give an example of how to structure this? 

Thank you for the update.

**Comment by pierrestoffe** [comment]
Yes sorry I realize it wasn't clear. The structure should be the following:
```
'languages' => [
    [
        'en' => 'siteAgroupA',
        'fr' => 'siteBgroupA',
        'nl' => 'siteCgroupA',
    ],
    [
        'en' => 'siteAgroupB',
        'fr' => 'siteBgroupB',
    ]
]
```

So with the example you gave:
```
'languages' => [
    [
        'nl' => 'siteADutch',
        'en' => 'siteAEnglish',
    ],
    [
        'nl' => 'siteBDutch',
        'en' => 'siteBEnglish',
    ],
    [
        'nl' => 'siteCDutch',
        'en' => 'siteCEnglish',
    ],
]
```

**Comment by pierrestoffe** [comment]
This feature has been released in v1.3.0 https://github.com/pierrestoffe/craft-language-redirector/releases/tag/1.3.0

**Comment by outline4** [comment]
Hi, 
I have different URLs for different sites and different languages. 

Eg:  
https://siteA.com (with de/fr)  
https://siteB.com (with de/fr)  
https://siteC.com (with de/fr)  
These sites are really different and they should not interfere with each other. 

All sites point to the same directory...

I've setup the languages array the following way: 

	'languages' => [
	    [
	        'de' => 'siteADe',
	        'fr' => 'siteAFr',
	    ],
	    [
	        'de' => 'siteBDe',
	        'fr' => 'siteBFr',
	    ],
	    [
	        'de' => 'siteCDe',
	        'fr' => 'siteCFr',
	    ],
	],

Site A in German is the default site. 

Now the following happens: 

If I go to https://siteB.com it will redirect to https://siteA.com/de 
If I go to https://siteC.com it will redirect to https://siteA.com/de 

In fact, when I omit the language trail it always redirects to the default site. 

BUT! While writing this, I've discovered that Safari, chrome and Firefox are treating this differently?  
So maybe it's a cache issue? 

Maybe I should ask a question first:   
What it the expected behavior? 

What I think it should be:  
When I go to https://siteB.com it should redirect to https://siteB.com/<languageOfBrowser>? 
What it does at the moment:  
it stays on https://siteB.com but the content is served in German (although i've set the site Url to /de)

Could you please help me out?  
Thanks

**Comment by pierrestoffe** [comment]
Hi @outline4, did you try clearing the Data Caches of Craft CMS (Utilities → Caches → Data caches → Clear caches)?
If you modified the config some time along the way it could create the issue you describe.

When you say that you have Safari, Chrome and Firefox are treating it differently, do you mean that it works correctly in one browser but not the other? Also, what happens when you use a private/incognito window?

**Comment by outline4** [comment]
Ok, so basically it comes down to one problem: 

I have defined all sites with a language "detector" (de or fr)
Like: 

siteADe = https://siteA.com/de  
siteAFr = https://siteA.com/fr  
siteBDe = https://siteB.com/de (default)  
siteBFr = https://siteB.com/fr  
siteCDe = https://siteC.com/de  
siteCFr = https://siteC.com/fr  

Only when I enter a page without the language detector (https://siteA.com, https://siteB.com or https://siteC.com) I will get into trouble.  
My inital thought was that Language redirector would handle this, but it does not seem to. 

I read an [article on stackexchage](https://craftcms.stackexchange.com/questions/23752/craft-3-multi-site-with-no-default-site) where brandon explains how to do this.

Any way, the solution that brandon provided does not match exactly my case (// find the first site that uses that language). So I came up with something custom... in twig (don't shoot me). 

Are you thinking of supporting a redirect like brandon explained... only more intelligent?

**Comment by pierrestoffe** [comment]
I think I understand, but it is unlikely that the plugin will handle this edge case in the near future. Additionally, defining this initial redirection from siteA.com to siteA.com/{language} would run faster if done in your server configuration directly instead of Twig.

So what I would recommend instead is defining a 301 redirection from siteA.com to siteA.com/de in your Nginx or Apache configuration (same for siteB.com and siteC.com). This plugin will then take over after that initial redirection, and take you to the correct language.
