### ISSUE TITLE
Redirect only during initial visit

### ISSUE THREAD

**Issue by piotrpog** [pierrestoffe/craft-language-redirector#13]
I think it would make more sense if automatic redirect occured only on initial visit.

Right now, when im "A" language user, i am automatically redirected to language "A". Which is good. But later i am UNABLE to take a peek into "B" language. I will just get redirected again to "A".

I know there is URL parameter for disabling redirects `ignore-lang` but that would need to be added to every link on website.

**Comment by pierrestoffe** [comment]
Hi @piotrpog. This seemed like a good theoretical idea to me as well at first, when I developed the plugin. But I then realized it was very hard to make this work in the real world, with actual user habits.

The way a visit would be identified as the first visit to my website (I'll call it website A) is "ok, you don't have the `language` cookie yet, so it must be your first time here". The `language` cookie is then created. If we were to implement your idea, it would mean that any language redirection would be bypassed from that point on. And that probably works very well when you are browsing the same website for a few minutes.

But the thing is that what this plugin is supposed to do is also redirect me to my preferred language if I click on a link from an external website that leads to website A. If the link references the EN version but I speak FR, and the `language` cookie is set to FR on website A, I want to be redirected to the FR version. Even more if I'm a returning visitor to website A. The issue is that the idea above would prevent that, and the plugin wouldn't be providing the service it's built for. Same thing for links in emails, in newsletters. Same also for social shares and many other, more specific contexts that are harder to list here.

I should also say that I've been using the plugin on dozens of projects now and I remember thinking multiple time that I did well not adding this feature. There is only one project for which I had to switch language in all links of one specific section. When that happened I added the `ignore-lang` URL parameter wherever it was needed.

Alternatively, I could have created a Twig filter that would have parsed the full content of the page and added the `ignore-lang` URL parameter to all URLs of the same domain.

Of course there might be very specific cases where you wouldn't care about the constrains listed above, but I won't be covering that need in this plugin unfortunately. If you really can't live without this feature the last resort is to create a fork of this plugin.

**Comment by piotrpog** [comment]
@pierrestoffe 
Let me present you alternative solution. This is behavour that this plugin has:
https://plugins.craftcms.com/country-redirect

Clicking link with `ignore-lang` added would create cookie that stops automatic redirecting. So unless user bothered to manually change language, redirects would still occur every time.

And even this behaviour would still be disabled by default, by config variable - it would just be usefull if it would be possible.
