### ISSUE TITLE
Use Blitz with Language Redirector

### ISSUE THREAD

**Issue by pierrestoffe** [pierrestoffe/craft-language-redirector#16]
If you are using Blitz and the Language Redirector plugin at the same time, you might want to read this wiki page: https://github.com/pierrestoffe/craft-language-redirector/wiki/Use-with-blitz.

**Comment by sandrodunkel** [comment]
Following these instructions I get the following error:
`Class "modules\businesslogic\LanguageRedirectorService" not found`

I used the [businesslogic template](https://github.com/doublesecretagency/craft-businesslogic). Everything is set up correctly since the example function (hide «all entries» tab) works perfectly fine.

**Comment by pierrestoffe** [comment]
@sandrodunkel I updated the code snippet on the [wiki page](https://github.com/pierrestoffe/craft-language-redirector/wiki/Use-with-Blitz).
The only change is the addition of the following on the first line:
`use pierrestoffe\languageredirector\services\LanguageRedirectorService;`

**Comment by sandrodunkel** [comment]
Lifesaver! Thank you, @pierrestoffe !
