### ISSUE TITLE
Multi-site plugin configuration not working

### ISSUE THREAD

**Issue by turnstylerj** [pierrestoffe/craft-language-redirector#20]
I have a site set up with a handful of languages using Craft Multisite as follows:
![Screen Shot 2022-06-09 at 3 18 09 PM](https://user-images.githubusercontent.com/42223501/172954604-2287c0a2-bc82-49f7-a89d-b93ace3c5216.png)

And the languages array in `config/language-redirector.php` is set to:
```
'languages' => [
	'en-US' => 'default',
	'en-GB' => 'englishUk',
	'en-AU' => 'englishAu',
	'fr-CA' => 'frenchCa',
	'de-DE' => 'germanDe',
	'ja-JP' => 'japaneseJp',
],
```

I am looking at an entry that's enabled on all sites, and am trying to test the redirect by setting my browser locale to French Canadian. I am currently using the Chrome plugin [locale switcher](https://chrome.google.com/webstore/detail/locale-switcher/kngfjpghaokedippaapkfihdlmmlafcc?hl=en-US) to make this easier, and opening https://manytools.org/http-html-text/browser-language/ returns:

```
Your browser's Accept-Language header:
fr-CA
```

I'm having a couple of issues:
1. No redirect is happening, and loading the default site does not redirect to the `fr-CA` site. Any way I can diagnose the issue?
2. If I dump `craft.languageSwitcher.getUrls()`, I can see an array of all the sites URLs, but each of them has the language appended as a query param like `?lang=en-US`, which is not necessary for our multisite URLs. I see in the config I can change the name of this query param, but can this be disabled?

**Comment by pierrestoffe** [comment]
@turnstylerj The config you shared looks correct, so it should work from there if the plugin is enabled in the CP.

One important thing to note is that the preferred Site is saved in the session. The preferred Site is the one that matches the language of the browser **when the session is initiated**, or the Site that the user selects in the language switcher. For example:
1. I type _mysite.com_ in the address bar of my browser, which is set to French (CA)
2. I'm redirected to _mysite.com/fr-ca_ automatically since a match is made with "fr"
3. The session will remember that the frenchCa Site is my preferred site and redirect all subsequent requests to this one
4. I click on English (UK) in the language switcher and am brought to the same page on the englishUk Site
5. The session will remember that the englishUk Site is my preferred site and redirect all subsequent requests to this one

This means that to properly test an automatic redirection after changing the language of the browser you would need to use a separate session. The easiest is to either empty your cookies or to use a private window (with independent cookies).

---

Regarding your second question: this URL parameter is needed to let the plugin know that we're forcing a new Site as preferred Site. Without it, the plugin would just reload the same page, on the same Site, since the automatic redirection to the currently-saved preferred Site would be naturally triggered.

To put it another way:
1. I type _mysite.com_ in the address bar of my browser, which is set to French (CA)
2. I'm redirected to _mysite.com/fr-ca_ automatically since a match is made with "fr"
3. The session will remember that the frenchCa Site is my preferred site and redirect all subsequent requests to this one
4. If I type _mysite.com/en-uk/about_ I'll be automatically redirected to _mysite.com/fr-ca/a-propos_ (the preferred Site), as expected
5. On that page, if the URL of the English (UK) entry is set to _mysite.com/en-uk/about_ in the language switcher and I click on it, I'll be once again automatically redirected to _mysite.com/fr-ca/a-propos_ (the preferred Site) as this is what the plugin is supposed to do
6. If the URL of the English (UK) entry is set to _mysite.com/en-uk/about?lang=en-UK_ though, the plugin will have a way to understand that you're trying to change the preferred Site to englishUk and will follow through

This should answer your two question, but let me know if something still isn't clear.

**Comment by turnstylerj** [comment]
Thanks for the quick response and the additional info on the query param!

I still can't seem to get the redirect to work being mindful of the session. I've been testing in private/incognito windows, can confirm I'm getting different `CraftSessionId` cookies, and am seeing expected locale results on other sites like Wikipedia and the browser language tester I mentioned in the original issue.

Can you think of any ways I can get some better logs/debugging information to track down what might be going on? This is my first multi-lingual site, so I unfortunately can't compare to a different Craft install.

**Comment by pierrestoffe** [comment]
@turnstylerj Could you maybe send me a dump of your database at mail[at]pierrestoffe.be so I try and reproduce it in a local env using the config values that you shared in your initial message?

Edit: Ah, and is it a Craft 3 or Craft 4 install?

**Comment by turnstylerj** [comment]
Sure, will do, thanks. And this is a Craft 3 install, specific versions:

```
"craftcms/cms": "3.7.44",
"pierrestoffe/craft-language-redirector": "2.0.0",
```

**Comment by pierrestoffe** [comment]
@turnstylerj Could you install v2.0.1 please?

I figured out that there would be no language match if the locales defined in the config files aren't lowercase. In your example you used "fr-CA" for example, which didn't work (also in my local environment), but it does work with "fr-ca". In the new release the plugin transforms the locale in a lowercase version before it is compared with the languages defined in the CMS.

**Comment by turnstylerj** [comment]
Awesome, thank you! Confirmed this is fixed in [v2.0.1](https://github.com/pierrestoffe/craft-language-redirector/tree/2.0.1).

**Comment by katsele** [comment]
Hi there, I experience the same issue. Currently, the website is not redirected to the right language. when I log `navigator.language` it gives me french, although the website's language is still English. Here is my config file:
```
'languages' => [
        'en' => '***DocEn',
        'fr' => '***DocFr',
    ],

// *** stands for the name of the website, which was hidden
```
And this is what I have in the backend: 
![language-redirector](https://user-images.githubusercontent.com/16958081/187384765-df8ba9ea-09d5-48d5-872f-6c1313a1fff2.png)

I'm a bit lost there.

**Comment by pierrestoffe** [comment]
@katsele What I see there looks correct.

Could you answer the following questions so we try and debug it together:
1. did you try in a private window as well, or in a different browser?
2. what happens if you remove your Craft session cookie?
3. did you name the config file language-redirector.php?
4. could you share the rest of your config file?

**Comment by katsele** [comment]
@pierrestoffe thanks for your swift answer. 

1. I tried in private windows, I also tried to remove the cookies directly via dev-tools (`Applications > Cookies`)
2. It doesn't seem to have an impact on the language
3. I created a config file named `language-redirector.php` in `/config/`
4. Sure: 
```
<?php
/**
 * Language Redirector plugin for Craft CMS 3.x
 *
 * Automatically redirect visitors to their preferred language
 *
 * @link      https://pierrestoffe.be
 * @copyright Copyright (c) 2018 Pierre Stoffe
 */

 /**
  * This file exists only as a template for the Language Redirector settings.
  * It does nothing on its own.
  *
  * Don't edit this file, instead copy it to 'craft/config' as 'language-redirector.php'
  * and make your changes there to override default settings.
  *
  * Once copied to 'craft/config', this file will be multi-environment aware as
  * well, so you can have different settings groups for each environment, just as
  * you do for 'general.php'
  */

return [
    // A list of all languages and their matching site
    'languages' => [
        'en' => '***DocEn',
        'fr' => '***DocFr',
    ],
    
    // The name of the URL query parameter
    'queryParameterName' => 'lang',
    
    // The name of the HTTP session key
    'sessionKeyName' => 'lang',
    
    // Should users with access to the Control Panel be redirected
    'redirectUsersWithCpAccess' => true,

    // Can users be automatically redirected or just use the plugin for language switching
    'canRedirect' => true,
    
    // The ID of the Entry that the getUrls method can default to when the current Entry is disabled in other Sites
    'defaultEntryId' => null,
    
];
```

**Comment by pierrestoffe** [comment]
@katsele Everything looks normal so I don't understand yet why the redirects aren't working. Could you send me your DB at mail[at]pierrestoffe.be so I install it on a blank Craft instance and figure out what's happening?
