### ISSUE TITLE
Manual Language Switcher

### ISSUE THREAD

**Issue by thomassausen** [pierrestoffe/craft-language-redirector#22]
The automatic forwarding seems to work. But then the user can no longer use the manual Language Switcher, which is currently realized via the Site Switcher plugin. 

It would therefore be best if automatic forwarding is used first, but as soon as the manual switcher is used, its values are adopted.

[https://github.com/doublesecretagency/craft-siteswitcher](https://github.com/doublesecretagency/craft-siteswitcher)

**Comment by pierrestoffe** [comment]
@thomassausen Did you try using this plugin's built-in language switcher ([see Wiki](https://github.com/pierrestoffe/craft-language-redirector/wiki/Language-switcher)) before installing the Site Switcher plugin? It automatically generates URLs in the format mentioned above, so I would advise to stick to it unless you require some additional logic that we don't cover already.

But in any case, I confirm that other plugins such as Site Switcher are compatible with this plugin, provided that you add `?lang=en` at the end of the URL that they generate. In that example `en` should be the language of the target Site.

Re-using some of [Site Switcher's documentation](https://github.com/doublesecretagency/craft-siteswitcher#dynamically-looping-through-all-sites) you would need to do the following:
```
{% set element = (category ?? entry ?? null) %}

<ul>
    {% for site in craft.app.sites.getAllSites() %}
        <li><a href="{{ siteSwitcher(site.handle, element) }}?lang={{ site.language }}">{{ site.name }}</a></li>
    {% endfor %}
</ul>
```

I didn't test it but should work.

**Comment by thomassausen** [comment]
I tried to use the built-in language switcher. But if I copy the Wiki example, my site won't render a language switcher.

I just copied 

```
{% set allLanguages = craft.languageSwitcher.getUrls() %}

<ul>
    {% for item in allLanguages %}
        <li>
            <a href="{{ item.url }}" hreflang="{{ item.id }}" lang="{{ item.id }}" title="{{ 'Switch to {language}'|translate({
                language: item.name
            }) }}">
                {{ item.nativeName|capitalize }}
            </a>
        </li>
    {% endfor %}
</ul>
```

Would be my best-case scenario, just using one plugin for language switcher and automatic redirects.

**Comment by pierrestoffe** [comment]
@thomassausen Can you confirm that you've created the language-redirector.php file and placed it in your config folder?

> 1. Copy the config.php file provided at the root of the plugin directory to the config folder of your Craft install.
> 2. Name it language-redirector.php.
> 3. Assign sites to languages in the languages array, either using their handle or their ID. For example: 'en' => 'english' or 'fr' => 5. Don't forget that the configuration file is multi-environment friendy, just like any other Craft config file.

**Comment by thomassausen** [comment]
1. Yes.
2. Yes.
3. Yes.

My language-redirector.php is like

```
<?php

return [
    'languages' => [
        'ar' => 'es',
        'bo' => 'es',
        'cl' => 'es',
        'co' => 'es',
        'cr' => 'es',
        'cu' => 'es',
        'do' => 'es',
        'ec' => 'es',
        'sv' => 'es',
        'gq' => 'es',
        'gt' => 'es',
        'hn' => 'es',
        'mx' => 'es',
        'ni' => 'es',
        'pa' => 'es',
        'py' => 'es',
        'pe' => 'es',
        'es' => 'es',
        'uy' => 'es',
        've' => 'es',
        'nl' => 'nl',
        'be' => 'nl',
        'en' => 'en',
        'fr' => 'en',
        'de' => 'en',
        'au' => 'en',
        'ca' => 'en',
    ],
];
```

There are three sites:
1. Name: NL / Handle: nl / Language: nl /
2. Name: EN / Handle: en / Language: en / Primary: Yes
3. Name: ES / Handle: es / Language: es /

**Comment by pierrestoffe** [comment]
In your language-redirector.php file you seem to be targeting country codes, instead of locales. This plugin only focuses on locales and redirects users based on their browser's language preferences. It will never redirect users based on the country in which their IP address is located because that information is much less relevant.

The locales that you set in the config file don't have to be country specific (e.g `es-ar`). You can use `es` and it will match all users that match any subset (`es-ar`, `es-bo`, `es-cl`,…).

As a result your config file should look like this:
```
<?php

return [
    'languages' => [
        'en' => 'en',
        'es' => 'es',
        'nl' => 'nl',
    ],
];
```

Could you try and confirm that it fixes your issue?

**Comment by thomassausen** [comment]
I changed the config file. But your snippet of the language switcher won't be rendered. Just empty <ul>

**Comment by pierrestoffe** [comment]
Ok, there seems to be something specific to your project that prevents it from working as it should. I'd need to dig a bit more into it to find a solution.

If possible could you send a dump of your DB + temporary access to your git repo (or ZIP) to mail[at]pierrestoffe.be? I'll take a look asap.

**Comment by pierrestoffe** [comment]
@thomassausen The issue was that you didn't have a homepage Section created in the CMS. The language switcher did appear on other pages, just not on the homepage. After creating a homepage Section in the CMS the issue got solved in my local instance.

The reason it was an issue is that this plugin finds the URL of other languages by querying Craft. It will 1) identify the URL of the currently-visited page, 2) find the Entry associated to that URL in the CMS, and 3) get the URL of each Site/language in which this Entry exists. In your case, since the homepage Entry didn't exist, the plugin just didn't know what to do and returned an empty array.

One extra note that may be useful during your tests: the automatic language redirection isn't enabled by default when you're logged into Craft (in the browser session). This doesn't affect much the language switcher itself, but for any upcoming test of the automatic redirects I would advise to test this plugin in private windows.

**Comment by thomassausen** [comment]
Thank you for your support. 

So I should use an Single or so, to create the homepage instead?

**Comment by pierrestoffe** [comment]
Yes that's it, a new Single where you check the _homepage_ checkbox and point to your existing homepage template.

Example on a multilingual site:
![CleanShot 2023-12-06 at 15 12 18@2x](https://github.com/pierrestoffe/craft-language-redirector/assets/1706605/19b382c6-13c8-446e-8826-2cebafdb894e)
