### ISSUE TITLE
Automatic redirect only working in firefox

### ISSUE THREAD

**Issue by lennonpuype** [pierrestoffe/craft-language-redirector#23]
Hi,

I don't know if I am overseeing anything, but I am really stuck on this.
So I read everything like the troubleshooting and what I am doing seems pretty right. I was testing in Chrome to let the primary site which is by default English, go to the dutch version because the OS and Browser are both in Dutch.

When seeing the troubleshooting tips on your wiki, I saw that testing on Firefox was recommended and when doing that, the same configuration works on firefox to redirect automatically. Am I overseeing any behaviour? It tested on Chrome, Edge and Safari, but there it doesnt work. It only does in firefox.

Except the Blitz part I kept the configuration pretty basic as your config.php is saying:
```
<?php
    use yii\base\Event;
    use pierrestoffe\languageredirector\services\LanguageRedirectorService;
    use putyourlightson\blitz\services\CacheRequestService;

    Event::on(
        CacheRequestService::class,
        CacheRequestService::EVENT_BEFORE_GET_RESPONSE,
        function (Event $event) {
            $languageRedirectorService = new LanguageRedirectorService();
            $languageRedirectorService->canRedirectVisitor();
        }
    );

    // ZODAT DE LANGUAGE SWITCHER WERKT MOET JE /?lang=language TOEVOEGEN NA DE SWITCH URL
    return [
        'languages' => [
            'nl' => 'nl',
            'en' => 'en'
        ],        
        'queryParameterName' => 'lang',
        'sessionKeyName' => 'lang',
        'redirectUsersWithCpAccess' => true,
        'canRedirect' => true,
        'defaultEntryId' => null,
    ]
?>
```

Here is the site configuration. I enabled the languages on all sections as well:
![Screenshot 2024-01-29 at 15 40 35](https://github.com/pierrestoffe/craft-language-redirector/assets/30866096/16bb509b-0a39-494b-a08a-83ad72f5e9cb)

**Comment by pierrestoffe** [comment]
Hi @lennonpuype,

I don't have a Blitz project running at the moment so didn't test Blitz support for the past 2 years at least. That could maybe be the reason.

Before digging further, could you confirm a few more things:
1. Does the same thing happen in private mode/window in Chrome/Safari/Edge
2. Do the redirections work if you add ?lang=nl or ?lang=en  in Chrome/Safari/Edge

**Comment by lennonpuype** [comment]
Hi Pierre,

Blitz is disabled on the local development so I kinda exclude that as the reason. But if you see that as a possible reason, Ill keep that one open 😉

To answer your questions:

1. The same thing is happening in a private window
2. Redirections do actually work using the `lang` parameter

**Comment by pierrestoffe** [comment]
@lennonpuype I tested a few scenarios but can't make sense of this issue.

If possible could you send a dump of your DB + temporary access to your git repo (or ZIP) to mail[at]pierrestoffe.be? There must be something specific about the project so I'll take a look asap.

**Comment by pierrestoffe** [comment]
@lennonpuype Thanks for sending the code and db dump. I tested your project locally and all redirects worked as expected (see video below, knowing that my browser's preferred language is English).

https://github.com/pierrestoffe/craft-language-redirector/assets/1706605/d6e6fd6d-1391-49b5-81e6-137c02a2b295

You'll notice that:
1. if I add /nl at the end of the URL, it redirects me to /
2. then if I add /nl?lang=nl at the end of the URL, it redirects me to /nl
3. then if I load /, it redirects me to /nl since I defined in point 2 that NL was my new preference
4. then if I add /nl?lang=en at the end of the URL, it redirects me to /
5. then if I load /nl, it redirects me to / since I defined in point 4 that EN was my new preference

If I understand correctly, point 1 is what doesn't work for you. But could you let me know if 3 and 5 are also not working as expected?

Also, could you add the above at the top of your language-redirector.php file and share the output please?
`dd(Craft::$app->getRequest()->getAcceptableLanguages());`.

**Comment by lennonpuype** [comment]
@pierrestoffe, just tested it again and it works. The behaviour of the redirect can just be so confusing.
Now I am testing again and have no clue why I didn't understand it earlier. Everything is just working fine 😛

Thanks for your help!
