### ISSUE TITLE
Confusion About Setup

### ISSUE THREAD

**Issue by garethjohnsdesign** [pierrestoffe/craft-language-redirector#4]
I'm trying to setup the plugin but a bit confused about the matching site array

I have 

```
return [
    // A list of all languages and their matching site
    'languages' => [
      'en' => '1',
      'en-US' => '2'
    ],
    
    // The name of the URL query parameter
    'queryParameterName' => 'lang',
    
    // The name of the HTTP session key
    'sessionKeyName' => 'lang'
];
```

is the site handle meant to be the 1 and 2 in this example. At the moment I have two sites, one UK (default one) and a US site, but not sure how to test this

**Comment by pierrestoffe** [comment]
@garethjohnsdesign In this array the key is the identifier of the language. It should ideally match a valid IETF language tag, but it's not a requirement. The value is then either the ID of a Site or its handle. I personally prefer to use Site handles as they are a bit more explicit.

**Comment by pierrestoffe** [comment]
I'll update the README to explain this with a bit more detail.

**Comment by pierrestoffe** [comment]
A mismatch occurred when mixing language-based and country-based IETF language tags. It has been fixed in https://github.com/pierrestoffe/craft-language-redirector/commit/11f6d99d624420041a835a07d164e9004a06f2dd which is part of the new 1.0.5 release.

Some documentation has also been added in the [Wiki](https://github.com/pierrestoffe/craft-language-redirector/wiki).
