### ISSUE TITLE
Switching between sites issue

### ISSUE THREAD

**Issue by intoeetive** [pierrestoffe/craft-language-redirector#7]
Hi @pierrestoffe 

I have encountered usability issue with the plugin.

So when I visit the site for the first time, I am getting redirected to my browser preferrable language, and that works perfectly.

But the site randomly has links to articles in different languages, not using language switcher (e.g. 'Read this article in German'). With plugin enabled, those links do not work, as I'm getting redirected back to my primary language.
I know I could add 'lang' parameter to the query, but that would make permanent switch (which is not something that I want atm).

Another similar issue is when I click entry url in control panel (the globe icon) in language other then my preferred, it also does not work (I'm being redirected)

Can you provide some solution for this? Maybe perform a redirect only on first visit, while the session variable is not set yet?

**Comment by pierrestoffe** [comment]
**Issue 1: Disabling the redirection after the session variable is set**

If I visit website A and the session variable is set to English, then click on a buttons on website B that links to the French version of website A, I expect to be redirected to the English version. This is the second most important feature of this plugin. Because of it I cannot disable the redirection on visits other than the first one.

The solution that comes to mind at the moment is to create a new URL parameter (different from `lang`) that would cancel the redirection.

**Issue 2: URLs from CP**

Two solutions here:
- disabling the redirection when the HTTP Referrer is a CP URL
- disabling the redirection when the visitor is logged into Craft (disabled by default but can be enabled in the plugin config file)

I'll look into which option makes the most sense in the context of this plugin.

Give me a few days to think about these two issues and look at what I can do.

**Comment by pierrestoffe** [comment]
The latest release introduces a solution for Issue 2 https://github.com/pierrestoffe/craft-language-redirector/releases/tag/1.1.0

I have an upcoming project that could also benefit from a solution to Issue 1 so I should be able to provide you with a solution in a few weeks.

**Comment by pierrestoffe** [comment]
The latest release introduces a solution for Issue 1 https://github.com/pierrestoffe/craft-language-redirector/releases/tag/1.1.2. You can now use the `ignore-lang` URL parameter to temporarily disable the automatic redirection.
